CREATE TABLE IF NOT EXISTS users (
  passport VARCHAR(12) NOT NULL,
  name VARCHAR(250) NOT NULL,
  date_of_birth DATE NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (passport)
);

CREATE TABLE IF NOT EXISTS credits (
  id CHAR(36) NOT NULL,
  date_of_issue DATE NOT NULL,
  end_date DATE NOT NULL,
  type_credit VARCHAR(32) NOT NULL,
  limit_credits REAL NOT NULL,
  arrears REAL,
  next_payment REAL,
  psc REAL NOT NULL,
  borrower_id VARCHAR(12) NOT NULL,
  is_current BOOLEAN NOT NULL,
  CONSTRAINT pk_credit PRIMARY KEY (id),
  CONSTRAINT fk_borrower_id
            FOREIGN KEY (borrower_id)
            REFERENCES users (passport) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS credits_bb (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  date_of_issue DATE NOT NULL,
  end_date DATE NOT NULL,
  type_credit VARCHAR(32) NOT NULL,
  limit_credits REAL NOT NULL,
  arrears REAL,
  next_payment REAL,
  psc REAL NOT NULL,
  borrower_id VARCHAR(12) NOT NULL,
  is_current BOOLEAN NOT NULL,
  CONSTRAINT pk_credit_bb PRIMARY KEY (id),
  CONSTRAINT fk_borrower_id_bb
            FOREIGN KEY (borrower_id)
            REFERENCES users (passport) ON DELETE CASCADE
);

